import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import TopBar from "../components/TopBar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <TopBar pageTitle="Main page" />
            <main>
                <p>
                    Get started by visiting the{" "}
                    <Link href="/web3/solana">
                        <a>Solana page</a>
                    </Link>
                </p>
            </main>

            <span className={styles.logo}>
                <Image
                    src="/vercel.svg"
                    alt="Vercel Logo"
                    width={72}
                    height={16}
                />
            </span>
        </div>
    );
};

export default Home;
